theme: jekyll-theme-slate
<link rel="shortcut icon" href="https://cdn.glitch.com/7fca4295-d232-43b3-b3ab-9070e3188aea%2Ffavicon%20(1).ico?v=1616629710562" type="image/x-icon">
<link rel="icon" href="https://cdn.glitch.com/7fca4295-d232-43b3-b3ab-9070e3188aea%2Ffavicon%20(1).ico?v=1616629710562" type="image/x-icon">
